### ISSUE TITLE
HathiTrust holdings

### ISSUE THREAD

**Issue by bertrama** [mlibrary/mgetit#1]
Initially posed by @varnum 

Something to explore; do we want to display HathiTrust holdings for items that are in the public domain and match an OpenURL?

**Comment by bertrama** [comment]
[Looks like HT support is broken at this time](http://findit.library.jhu.edu/resolve?umlaut.referent_id=34190606&url_ver=Z39.88-2004&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&ctx_ver=Z39.88-2004&ctx_tim=2016-05-02T16%3A13%3A45-04%3A00&ctx_id=&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rft.place=United+States&rft.atitle=Sex+role+characteristics+of+female+governor%27s+school+students+&rft.spage=32&rft.jtitle=The+Gifted+Child+Today+v.+14+%28July%2FAugust+1991%29+p.+32-5&rft.date=1991&rft.issn=08929580&rft.genre=article&rft.volume=14&rft.epage=35&rft.aulast=Howard-Hamilton&rft.aufirst=Mary&rft.auinit=F&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rfr_id=info%3Asid%2Flibrary.jhu.edu%3Axerxes+%28+Education+Full+Text%29).

I pulled that [example url from Jon Rochkind's blog](https://bibwild.wordpress.com/2008/10/16/umlaut-digital-book/).

**Comment by jonearley** [comment]
Not a feature anymore.
