### ISSUE TITLE
Use database rankings from 360 Link

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#12]
These aren't in the API, but is there a way to grab them (even manually, periodically) from the 360 Link client center, and apply them to our display? 

Alternative:
Pick the ones we HATE and make them appear last (Judy/Kenyon can help with this)

**Comment by bertrama** [comment]
[Fixed in eed7caf2def336d9eb0829ae89880ef7c6879ceb](https://github.com/mlibrary/umlaut-three-sixty-link/commit/eed7caf2def336d9eb0829ae89880ef7c6879ceb)
