### ISSUE TITLE
Deduplication of results from same database platform

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#14]
360 Link lets us remove multiple results from the same database platform, showing only our most preferred database for that platform. (So if there are 5 Gale databases, only 1 will show). Can we do this in Umlaut?  

[Feedback from team meeting today]

**Comment by bertrama** [comment]
Problems was:  The priority isn't available in the api, and isn't known to me.

Kenyon gave me a spreadsheet with the priorities.  I'll need to put them in a format our umlaut plugin can handle, and use them there.

**Comment by bertrama** [comment]
[Fixed in eed7caf2def336d9eb0829ae89880ef7c6879ceb](https://github.com/mlibrary/umlaut-three-sixty-link/commit/eed7caf2def336d9eb0829ae89880ef7c6879ceb)
