### ISSUE TITLE
"Get Item" buttons

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#15]
When we can identify as an article, use "Read Article"

When we can identify as a chapter, use "Read Chapter"

If there are other common types, use "Read [type]"

Otherwise, use "Go to Item"

**Comment by jonearley** [comment]
Added in "Read Article" when it can be identified.

**Comment by varnum** [comment]
How about "Read Chapter", for things like this?
https://earleyj.www.lib.umich.edu/testapp/mgetit/go/324


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by jonearley** [comment]
@varnum Yep, added!
