### ISSUE TITLE
Document Delivery label

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#19]
Change to match what's in current 360 Link interface: 

	
Request Delivery Service (Interlibrary Loan, 7FAST)

**Comment by jonearley** [comment]
Similar to the report a problem copy, I think this change would be worse for the end user.

> [Request Delivery Service (Interlibrary Loan, 7FAST) (Fees apply for undergraduates)](url)

This is closer to what we call these things internally, but I think this language takes extra effort to understand. It's wordy, full of our internal naming, therefore takes extra effort to understand.

> [Request a copy delivered](url)

Gets to the useful point of the service and is easily readable. I think the brand names and cases for fees should be handled down the line inside the document delivery services. When someone gets into document delivery.

I like to keep online copy as brief and conversation-like as possible. It helps with readability and lets the user scan the page.

Examples of each:

![request-a-copy-delivered](https://cloud.githubusercontent.com/assets/1678665/17595731/348bca26-5fbc-11e6-9dea-c2109905d228.png)

![request-a-copy-delivered-2](https://cloud.githubusercontent.com/assets/1678665/17595733/36382d24-5fbc-11e6-8cbf-2d3682d50055.png)

@bnhowell, @heidisb for UX input.

**Comment by heidisb** [comment]
I definitely agree with you about the institutional jargon, @jonearley. I like the change to a more conversation tone, but would suggest: Request to have a copy delivered. You may get pushback and need to meet in the middle by including the service names in parentheses, but changing the copy away from Request Delivery Service would still be an improvement.

Is this text something that always appears? If so...it does seem preemptive to include the (Fees apply for undergraduates) since they only have to pay for 7Fast, not Interlibrary Loan (right?).

**Comment by jonearley** [comment]
I agree with you @heidisb and think that's a fair compromise. Below is an example with the change. It's live here: [https://earleyj.www.lib.umich.edu/testapp/mgetit/go/192](https://earleyj.www.lib.umich.edu/testapp/mgetit/go/192)

![request-a-copy-delivered-3](https://cloud.githubusercontent.com/assets/1678665/17598729/dc2ff1e6-5fc9-11e6-8138-b7d5827cefdc.png)

**Comment by varnum** [comment]
The text is good. What about the fee info for undergrads?


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by heidisb** [comment]
Like that! My q about the fee info for undergrads...is this text something that **always** appears? If so...it seems preemptive to include the the fee info since they only have to pay for 7Fast, not Interlibrary Loan (right?).

**Comment by jonearley** [comment]
Information about fees seems to me too fine of a detail to include on a page leading to the service. The document delivery services should handle that type of information in my opinion.

It helps keep the copy brief.

**Comment by varnum** [comment]
It's complicated:  http://www.lib.umich.edu/interlibrary-loan/fees-services

"Fees may apply for undergraduates" is probably truthful, and important
up-front. (At least, it's been so deemed in Mirlyn, where we orchestrated
Get This to be very clear, based on who you were, what we offered with what
language.)


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by varnum** [comment]
I'm OK leaving it off, pending feedback.


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by heidisb** [comment]
Gah. That table. I know the PARC/ERSC side of things likes to warn students about potential costs up front. Even though I **hate** it and feel like it tries to push students away from using the service. What about including a fees statement in the gray parentheses (i.e. there but not adding as much clutter):

(Interlibrary Loans, 7Fast -- fees may apply for undergraduates)

**Comment by varnum** [comment]
Yeah, I know. I don't even understand what most of the services are....


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by heidisb** [comment]
Thus the need for that user research MLDD put in the FD card for...I'm excited about that
