### ISSUE TITLE
What to do when catalog and document delivery links are not available?

### ISSUE THREAD

**Issue by jonearley** [mlibrary/mgetit#21]

**Comment by varnum** [comment]
What's the scenario for this?

**Comment by jonearley** [comment]
I'm having trouble finding the example now, but earlier I had an MGet It page without catalog and delivery links available.

**Comment by jonearley** [comment]
It's possible it was a local development issue. I can't repeat the issue at: [https://earleyj.www.lib.umich.edu/articles/search](https://earleyj.www.lib.umich.edu/articles/search)

**Comment by jonearley** [comment]
This issue isn't relevant anymore. It seems to have been just some local development confusion on my end.
