### ISSUE TITLE
Point "MGet It" link in site navigation to new form

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#23]
We mustn't forget to make the Citation Linker -- what you get to when you click "MGet It" in the library site's top-of-page navigation -- work properly. It currently points to http://mgetit.lib.umich.edu.proxy.lib.umich.edu/?SS_Page=refiner&SS_RefinerEditable=yes , which immediately redirects (thanks to a DNS entry we maintain) to http://dl2af5jf3e.search.serialssolutions.com.proxy.lib.umich.edu/?SS_Page=refiner&SS_RefinerEditable=yes

Once we take over mgetit.lib.umich.edu and point it to Umlaut, that reference won't work.

I'm betting Albert's the right one to coordinate this. Maybe Eliot?

**Comment by varnum** [comment]
See issue #30.

**Comment by varnum** [comment]
MGet It link in site navigation should ultimately be to
https://mgetit.lib.umich.edu/citation-linker

**Comment by bertrama** [comment]
I think Jon was planning on that living on www.lib, iirc.  Is that problematic?

**Comment by jonearley** [comment]
@bertrama that's correct. I created the openurlform standalone, so separate from the Umlaut code base. It made development easier and would take some time to integrate the two. I think it's OK to keep the separated.

I thought the link resolver could live at `www.lib.umich.edu/link-resolver`.

**Comment by jonearley** [comment]
Albert added the link resolver form to live here http://www.lib.umich.edu/citation-linker/

**Comment by varnum** [comment]
It should all be at mgetit.lib.umich.edu -- the form at
mgetit.lib.umich.edu/citation-linker, the resolver at
mgetit.lib.umich.edu/resolve?


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by varnum** [comment]
Done (in Mirlyn as well).
