### ISSUE TITLE
"Find It" embedded in an error message(s)

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#25]
https://earleyj.www.lib.umich.edu/testapp/mgetit/go/165

Warning message says: "Warning: Find It does not know about a journal with this name. Please check your entry."

Can we replace all of the "Find It" instances with "MGet It" ? Should this be a setting?

**Comment by jonearley** [comment]
@bertrama I was looking for the appropriate place is settings/config to change Find It to MGet It, but wasn't sure the right way to go about it.

**Comment by bertrama** [comment]
I believe that's in the controller: 5e3c5a546f1084a0a079271b1e02dc7e51bb8586
