### ISSUE TITLE
DOI search comes up with wrong results

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#26]
10.6017/ital.v34i1.5607

Works in ArticlesPlus: https://www.lib.umich.edu/articles/search?kw=10.6017/ital.v34i1.5607

Wrong item in MGet It: https://earleyj.www.lib.umich.edu/testapp/mgetit/go/166 (when entered from http://earleyj.www.lib.umich.edu/testapp/mgetit/ )

**Comment by bertrama** [comment]
We aren't presently updating the referent data with data from 360Link.  I'll look into that, but will have to be careful:  Sometimes there is disagreement among 360Link's results.

**Comment by jonearley** [comment]
- [] Create a friendlier error message

**Comment by bertrama** [comment]
[DOI:10.6017/ital.v34i1.5607](https://earleyj.www.lib.umich.edu/testapp/mgetit/resolve?version=1.0&sid=sersol%3ARefinerQuery&citationsubmit=Look+Up&url_ver=Z39.88-2004&l=DL2AF5JF3E&SS_LibHash=DL2AF5JF3E&rfr_id=info%3Asid%2Fsersol%3ARefinerQuery&SS_ReferentFormat=JournalFormat&rft_id=info%3Adoi%2F10.6017%2Fital.v34i1.5607&rft.genre=article&SS_doi=10.6017%2Fital.v34i1.5607&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal)

[ISBN:9781489961761](https://earleyj.www.lib.umich.edu/testapp/mgetit/resolve?sid=sersol%3ARefinerQuery&rft.isbn=9781489961761&citationsubmit=Look+Up&url_ver=Z39.88-2004&l=DL2AF5JF3E&SS_LibHash=DL2AF5JF3E&rfr_id=info%3Asid%2Fsersol%3ARefinerQuery&SS_ReferentFormat=BookFormat&rft.genre=book&SS_isbnh=978-1-4899-6176-1&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook)
