### ISSUE TITLE
Need a link for found a problem

### ISSUE THREAD

**Issue by jonearley** [mlibrary/mgetit#27]
This currently doesn't link to anything. @varnum, should this link to a qualtrics form?

**Comment by varnum** [comment]
See this in Slack:  https://mlit.slack.com/archives/umlaut/p1470762663000056

Use the URL syntax from current ArticlesPlus problem links, with addition the argument noted in Slack.

**Comment by jonearley** [comment]
@bertrama could you help make this link available in the umlaut views so I can add it to the UI? We could do this together also like with the catalog links if you prefer.

**Comment by bertrama** [comment]
This should already be there: aac991da88d378317a22015175aad4a1073e3582

service_type_value is 'help'

**Comment by jonearley** [comment]
@bertrama thank you! Added to the designs: 827172fab412e57a580277e96f88824645a47d37
