### ISSUE TITLE
Test the real thing

### ISSUE THREAD

**Issue by jonearley** [mlibrary/mgetit#32]
@bnhowell can gather scenarios and cases from the project team (mainly service experts) to make sure our new link resolver is meeting staff expectations.

**Comment by jonearley** [comment]
I can go along with Ben if I'm available to take notes during testing.

**Comment by jonearley** [comment]
**Working Umlaut User Testing Moderator Script**
https://docs.google.com/document/d/1V_0UnpO3otLmBmCQkubOVsegp9plcQJqRpKqonMnYRc/edit?ts=57bdb43b#heading=h.x3ixihf3572z

**Comment by jonearley** [comment]
Update: @bnhowell conducted user testing this week.

**Comment by varnum** [comment]
Do we have any sense of how well (to be optimistic) users understand the
new site?


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by jonearley** [comment]
From the two users I sat in on during Ben's user testing the new site made sense to them.

**Comment by varnum** [comment]
User feedback is summarized in [Umlaut User Studies](https://docs.google.com/spreadsheets/d/1gtUZcoLExSlZ8QoMWpv6sSuR4EKq288g_bc2f29lr74/edit#gid=0).
