### ISSUE TITLE
Final Accessibility Review

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#33]
Before public launch, a final accessibility review.

**Comment by varnum** [comment]
See the [test cases document](https://docs.google.com/document/d/1l7nmOyJhs-_Xp01y-EYlItLgQ5juc5szdv6BBfXttBg/edit).

**Comment by varnum** [comment]
Colin completed the review; here are the things to update:


None of these are critical issues, but here are some things to fix for accessibility:

- The page needs a min-width to prevent it from getting overly squished on tiny screens/windows.
- The content in the site-header should have a max-width to prevent the MLibrary logo and permalink from moving too far away from the content.
- The page footer should be in a footer tag.
- Citations should be in cite tags.
- The "Multiple Matches" header should be an h2 tag.
- "Go To Journal", "Go To Book" and similar links need unique text to differentiate them when there are multiple on the same page. This can be done with hidden link text following the visible link text. Something like "from Routledge handbooks online"

**Comment by varnum** [comment]
@jonearley -- are these changes in place?

**Comment by jonearley** [comment]
@varnum Not yet.

**Comment by varnum** [comment]
Can these changes be made before the end of December? It would be nice to check them off the list. @jonearley

**Comment by jonearley** [comment]
I fixed and addressed all the accessibility concerns Colin had listed. They were mostly minor updates and so it was quick to implement. @varnum
