### ISSUE TITLE
Fix links to "M" and "Library" in top-of-page navigation

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#34]
The logos should mimic behavior on the library website: 

- The "Block M" should go to http://umich.edu/ , with a title of "University of Michigan"
- The "Library" should go to http://www.lib.umich.edu , with a title of "U-M Library"

Though.... Should the header mimic [Blogs](http://www.lib.umich.edu/blogs) with the stacked "M Library", a vertical bar, and "MGet It" in text? Not sure what that would do with the tagline....

**Comment by jonearley** [comment]
@bnhowell, @Treevore If UX thinks this is a good idea, let me know and I'll implement.

**Comment by bnhowell** [comment]
Just talked with Trevor and Ken's description looks good to implement. Let's keep consistent behavior with the library homepage top navigation.

**Comment by jonearley** [comment]
Alright thanks! I'll work on it.

**Comment by jonearley** [comment]
@Treevore could you help create an SVG and PNG version of the M and "Library, University of Michigan" (white) logos? Background can be transparent.

<img width="258" alt="screen shot 2016-08-23 at 4 34 02 pm" src="https://cloud.githubusercontent.com/assets/1678665/17908674/72420956-694f-11e6-9ac6-0c1c023e52ab.png">

**Comment by Treevore** [comment]
Github Isn't letting me upload the SVG so I will try Slack.

**Comment by jonearley** [comment]
Thanks @Treevore!

I've added in the new graphics and links.
