### ISSUE TITLE
Revise Footer text

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#35]
The Umlaut Footer text is currently "Powered by Umlaut. Using services from Google Books, SerialsSolutions and others [D]", with Umlaut, Google Books, and Serials Solutions links to those respective sites. "[D]" links nowhere. 

Should the footer contain our normal footer information, if we have a "normal"? [Blogs](http://www.lib.umich.edu/blogs) and [Guides](http://guides.lib.umich.edu/) have similar content to each other. I'm happy to keep the application credit, too (like we do in [Omeka](http://www.lib.umich.edu/online-exhibits)). 

If we just keep the current footer, at a minimum it needs to be a sentence:
"Powered by Umlaut using services from ..."

**Comment by bertrama** [comment]
The I believe that the [D] is a toggle to display debugging messages. Johns Hopkins's umlaut presents it in production.  That said, we don't provide any debugging information to show.

**Comment by jonearley** [comment]
I'm OK showing the basic "Powered by Umlaut using services from..." for the footer. I can add back in the debug information if that's desired.

**Comment by varnum** [comment]
What about the copyright and contact information?


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by jonearley** [comment]
This doesn't seem like a high priority. I think the footer is ok as is. Could we close this issue?

**Comment by varnum** [comment]
Let's get rid of everything but "Powered by Umlaut" in the footer.
