### ISSUE TITLE
Add Get Item Label Configuration

### ISSUE THREAD

**Issue by jonearley** [mlibrary/mgetit#36]
Copied from an email with Albert:

> I was going to recommend that.  Probably for all of the strings we have in the interface, really.  I18n is the standard way to do that, so you'd add them to config/locales/en.yml:
> 
> ```yaml
> en:
>   umlaut:
>     call_to_action:
>       book:
>         book: Read Book
>       journal:
>         article: Read Article
>         journal: Read Journal
> ```
> 
> Then in your code, you'd do something like:
> 
> ```erb
> <%= t("umlaut.call_to_action.#{format}.#{genre}") %>
> ```

**Comment by bertrama** [comment]
For defaults, I might try:

```yaml
en:
  umlaut:
    call_to_action:
      default: Get This
```
then the t() call might be:

```erb
<%= t("umlaut.call_to_action.#{format}.#{genre}", default: 'umlaut.call_to_action.default') %>
```

**Comment by jonearley** [comment]
@bertrama I think that default syntax is a little off, it just displays the string "umlaut.call_to_action.default" and not the translation.

**Comment by bertrama** [comment]
[Looks like it has to be a symbol for it to do a lookup](http://guides.rubyonrails.org/i18n.html).  I'm not sure how far it'll backtrack up the structure, worth trying `default: :default` and see if anything shakes out.  Otherwise it'll be more like

<%= t("#{format}.#{genre}, scope: [:umlaut, :call_to_action], default: :default %>

**Comment by jonearley** [comment]
@bertrama I'll give that a try. Thanks!

Let me know when `format` and `genre` are available on each bundle. Will they be under service_data?

**Comment by bertrama** [comment]
Should be when you update umlaut-three-sixty-link, and yes, it should be under service_data.

**Comment by jonearley** [comment]
Thanks to some help by @bertrama we have a configuration file that handles the labeling of "Go To Item" buttons. 

The config file: https://github.com/mlibrary/mgetit/blob/mgetit-designs/config/locales/en.yml

@varnum let me know if these labels look right. I matched some of the common formats and genres following the matrix.

**Comment by varnum** [comment]
Yes, I think so -- haven't found all the permutations "in the wild", but from the configuration and what I've seen, looks good.

**Comment by bertrama** [comment]
https://dev.www.lib.umich.edu/testapp/mgetit/resolve?ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2Fsummon.serialssolutions.com&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&rft.genre=bookitem&rft.title=Fowler%E2%80%99s+Concise+Dictionary+of+Modern+English+Usage&rft.atitle=magic&rft.date=2016-01-01&rft.pub=Oxford+University+Press&rft.isbn=9780199666317&rft.externalDocID=10_1093_acref_9780199666317_013_2346&rft.link_model=DirectLink&rft.summon_id=FETCH-oup_oro_10_1093_acref_9780199666317_013_23463&rft.bookmark=ePnHCXMw42LgTQStzc4rAe_hSmGEHHID7BZYgPYMWDKDj7UBNrLNgKmJAxrzwHrYzMLc3JCTgTU3MR206tjYzTXE2UM3v7QgPr8oPx4yVWocnwhsSqXFQwyEmGEeD2zExBsZm4AO8iRHFwBbKC0i&rft.link=http%3A%2F%2Fumich.summon.serialssolutions.com%2F2.0.0%2Flink%2F0%2FeLvHCXMwtV1NS8QwEB0WPSgKKip-wrJ4NGyTbLZV1oVFt4p403vI5uNmC-uK-O-dadpK8bQHz2naCR0mr5P3XgGuMuWCNcoxE8SCjXBLIBJAyrhUxlor0iwhNfLDi5jl6jmX8x40B-3EqiwrpVz3LxvUJm_Mj4YG8VQga9iEKLS4ZXKyIeRkRcjjIOsMMs-EHJEtN8ILon09zl6bnEMEMM7SlEe3nTghq4152htE8dvOb1nN91pTkMg2qWydmu7gX0PH_1zWPmy1nrQH0PPFIdxOsBoVfUv4-25QpyAjmS_RQr8ZYmHMCMe-MKCPwfTdYJGdDGnO9AhkPn-7f2K4YF0uSx0PqaWuAtCdADTCR00hyGPYNUTIL1aVcM-dQB-BiFcLE1TisU4IZTLv7A3Hz5dxkFyFU7he5xFn611-DtuIbOpeyQVsrJaf_hI2q1f0A9jht4s

Not that you can test it now, but this one is for a book chapter ("Book item").  One of the links has "Go to Journal" text.

**Comment by jonearley** [comment]
Reviewed and completed label configuration with @varnum.
