### ISSUE TITLE
ReportSource for Qualtrics "Report a Problem Link" in ArticlesPlus

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#39]
This is related to Umlaut... The "problem report" links have a "ReportSource=MGetIt" in the URL that's passed to Qualtrics. Could something similar be added to ArticlesPlus: "ReportSource=ArticlesPlus" so that we can easily report on problems reported from the two (and possibly other, future) sources?

**Comment by bertrama** [comment]
Isn't ArticlesPlus going to send people to MGetIt when it launches?

**Comment by varnum** [comment]
Good point. I was thinking the existing "report a problem" link would remain in AP, and should be identified as such. The AP "report a problem" link has made its way into training materials, so might need to persist a little while; if that's the case, we'll need to track the sources.

I'll need to check with with Ask a Librarian and EAU about removing it, which I'll do. @bnhowell

**Comment by varnum** [comment]
OK, after talking with Karen R-S and Kenyon, we're agreed -- as part of the launch of MGet it, we'll remove the "report a problem" link from ArticlesPlus and rely solely on the one in MGet It.

So I'll close this, and create a new ticket to reflect the new task.
