### ISSUE TITLE
Add "by" before authorship information in citation

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#40]
From Qualtrics feedback

**Comment by varnum** [comment]
Adding Ben & Trevor

**Comment by bnhowell** [comment]
I also had a few students who asked for descriptive text before info in the citation. 
Here's what I propose for better clarity: 

By: (Author) 
Journal: (Journal, Volume, Date) 
ISSN: (ISSN)
Resource: (Resource type when known)

Here's a screenshot:
![mget it citation design 2 0](https://cloud.githubusercontent.com/assets/16804543/18636408/ad1fffe4-7e56-11e6-9c8a-2b5b00e45963.png)

**Comment by jonearley** [comment]
Okay I agree with this change.

**Comment by varnum** [comment]
Thanks -- looks like a good approach to me.

**Comment by jonearley** [comment]
Added.

**Comment by varnum** [comment]
I don't see this on dev.www yet...

**Comment by bertrama** [comment]
dev.www.lib is the stable install, the last update there was probably last week.
