### ISSUE TITLE
Add date of publication to citation summary

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#41]
Qualtrics survey -- ID 1, request 3. (Don't know what citation was requested, sadly).

**Comment by varnum** [comment]
Adding Ben & Trevor

**Comment by bnhowell** [comment]
After reading this feedback in the survey this feels like a systems issue rather than UI.

**Comment by varnum** [comment]
OK -- let's see if we can fix it. Calling it a bug & enhancement, to cover my bases, and adding Albert.

**Comment by jonearley** [comment]
We don't show a date in the citation currently. I do see a field "date" in the data that I assume is the publication date. I can add that in?

**Comment by jonearley** [comment]
![link_resolver_date](https://cloud.githubusercontent.com/assets/1678665/18642638/6ed1f74c-7e6f-11e6-89ed-0c06aa3fa515.png)

Example with labels on citation metadata. Including publication date.

**Comment by bnhowell** [comment]
@jonearley Is there a reason the publication date is below ISSN? Publication Date is about article and I wonder if it would be best below by: (author). 

Several users have asked for publication date in user studies. (Could be a high priority in the citation)

**Comment by jonearley** [comment]
I looked at the [Articles Record Detail Display Specifications](https://docs.google.com/a/umich.edu/document/d/1Aa0XM9kVWcdzqq9MRcTSBKPe1HKZUjQut-MVIlKK80A/edit?usp=sharing) document and it seems like it is best right above the journal information. I've updated the UI to reflect that.

<img width="494" alt="screen shot 2016-09-19 at 2 00 50 pm" src="https://cloud.githubusercontent.com/assets/1678665/18643106/9793d964-7e71-11e6-8e40-9f361a99447a.png">

**Comment by varnum** [comment]
Although the search specs have very little to do with field order, I think putting the date after author, before the journal, is fine.

**Comment by jonearley** [comment]
This has been added, right before the journal.

**Comment by varnum** [comment]
Needs more consistency; it's not just journal articles that have useful dates. See for example, multiple links from [this AP search](https://dev.www.lib.umich.edu/testapp/mgetit/go/332) from http://dev.www.lib.umich.edu/articles/search?kw=%22thurgood+marshall%22+%22bill+clinton%22):

A [reference item](https://dev.www.lib.umich.edu/testapp/mgetit/go/332) 
A book chapter ([this one](https://dev.www.lib.umich.edu/testapp/mgetit/go/340) or [that one](https://dev.www.lib.umich.edu/testapp/mgetit/go/342))
A [data set](https://dev.www.lib.umich.edu/testapp/mgetit/go/338)

**Comment by jonearley** [comment]
Those linked examples are to dev. To see the recent changes go to earleyj.

Make it more consistent in what way? So far if I have information about a journal I add the label "Journal: " before the metadata.

**Comment by varnum** [comment]
I don't see dates for reference, book chapter,  or data sets in MGet It, al though dates are shown in the ArticlesPlus citations.

**Comment by bertrama** [comment]
Dev has been updated.  Dates are visible.

**Comment by varnum** [comment]
I'm seeing dates on all the types now, on dev. Thanks! I'm OK with closing this one.
