### ISSUE TITLE
Change "Ask a Librarian" descriptive text

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#46]
A request from Karen R-S:

> Hi Shevon, Ken and Harold! I have one strong concern about
> the link resolver page, which I hope you can change before
> releasing it ...
> 
> We have learned over the years that "chat" means something
> quite different to students than we think. Because of an
> increase of inappropriate contacts and non-library related
> conversations in our instant messaging service over the
> years, we have very purposefully removed all mentions of
> "chat" on web pages, in handouts, etc. -- we currently use
> instant messaging to describe the interaction between
> students and library staff.
> 
> To minimize the possible negative impact on the Ask a
> Librarian services, please change the sentence under the Get
> Help heading, to remove "chat." I suggest changing the
> statement to something more like: **Contact a librarian about
> this record, about finding online articles, or about your
> library research.**

@bnhowell , what do you think?

**Comment by bnhowell** [comment]
I think the copy needs tweaking. Possibly: _**Chat with a librarian for help with this record or your library research.**_  [the about adverb in the copy above reduces readability. A list of what librarians provide could work better on the chat page itself.]

**Comment by jonearley** [comment]
@bnhowell We will need a strong argument to keep using the word "chat" if that's what you think is best.

**Comment by varnum** [comment]
I agree, "item" works well. Ben's abbreviated language works for me. 

Make it so!

**Comment by jonearley** [comment]
Updated. [see example at earleyj](https://earleyj.www.lib.umich.edu/testapp/mgetit/resolve?umlaut.referent_id=1036&url_ver=Z39.88-2004&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&ctx_ver=Z39.88-2004&ctx_tim=2016-09-06T14%3A15%3A10-04%3A00&ctx_id=&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rft.atitle=Tetrahedral+Tetris&rft.date=2013-01-01&rft.eissn=1545-2786&rft.externaldbid=IAO&rft.externaldocid=318020837&rft.genre=article&rft.issn=00030996&rft.issue=1&rft.jtitle=American+scientist&rft.l=SK8ES4MC2L&rft.localeid=1033&rft.paramdict=en-US&rft.PP=true&rft.spage=3&rft.SS_authors=Moore%2C+Cristopher&rft.SS_eissnh=1545-2786&rft.SS_issnh=0003-0996&rft.SS_LibHash=SK8ES4MC2L&rft.SS_PostParamDict=disableOneClick&rft.SS_ReferentFormat=JournalFormat&rft.SS_RequestType=1&rft.SS_sid=info%3Asid%2Fsummon.serialssolutions.com&rft.SS_source=56&rft.title=American+Scientist&rft.volume=101&rft.au=Moore%2C+Cristopher&rft.aulast=Moore&rft.aufirst=Cristopher&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rfr_id=info%3Asid%2Finfo%3Asid%2Fsummon.serialssolutions.com)

**Comment by varnum** [comment]
Thanks!

**Comment by varnum** [comment]
Closing.
