### ISSUE TITLE
Test & Provide Path to Use Health Sciences-focused tools and apps

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#49]
Testing software and apps that are utilizing access to our full text journal holdings to ensure that there is no interruption of service/utility (including Endnote Find Full Text, READ by QxMD, and others identified by THL Informationists)

**Comment by varnum** [comment]
@bertrama We've done the testing and configuring we can do, right?

**Comment by bertrama** [comment]
I believe we have.

**Comment by varnum** [comment]
Closing.
