### ISSUE TITLE
Use IEDL when there is one

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#5]
When 360 Link's API provides an IEDL for a resource, make that the default (first) "Get *" link. Any resolved targets should be "more options", expandable to be accessible if the first link isn't satisfactory.

**Comment by bertrama** [comment]
To clarify from our discussion earlier:

360Link's api doesn't look like it gives IEDLs.

ArticlesPlus has its direct links, and we can tell Umlaut about them.

**Comment by varnum** [comment]
If the IEDL appears in the API (per Eddie's email last night), could it be displayed in the interface with some cue (for testing) that it's an IEDL, not a traditional resolved link? @jonearley

**Comment by jonearley** [comment]
Note to self: Setup UI to look for direct link.
