### ISSUE TITLE
Permalink shouldn't include proxy address

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#52]
So on this OpenURL
https://mgetit-lib-umich-edu.proxy.lib.umich.edu/resolve?ID=doi%3A10.1016%2Fj.socnet.2016.01.002&atitle=Bayesian%2520exponential%2520random%2520graph%2520models%2520with%2520nodal%2520random%2520effects.&aulast=Thiemichen%2C%2520S.&date=20160701&genre=article&issn=03788733&issue=&pages=11-28&sid=EBSCO%3APsycINFO%3A2016-21231-003&spage=11&title=Social%2520Networks&volume=46

The permalink is https://mgetit-lib-umich-edu.proxy.lib.umich.edu/go/84

When it should be https://mgetit.lib.umich.edu/go/84

**Comment by jonearley** [comment]
https://github.com/mlibrary/mgetit/blob/master/app/views/umlaut/_header.html.erb

@bertrama could you update the `render_umlaut_permalink_url` value I use in the header to instead use the shorter  `mgetit.lib.umich.edu` URL?

**Comment by jonearley** [comment]
Albert fixed this.

**Comment by varnum** [comment]
Sorry -- I jumped the gun on closing this.

**Comment by jonearley** [comment]
@varnum the OpenURL example linked here has cached the old permalink. If you look at any OpenURL that hasn't been cached it is fixed. Umlaut caches almost everything.

**Comment by varnum** [comment]
Hmmm... Searches I do at Web of Science -- new ones -- via a proxied link
end up at MGet It with a proxied link, and the permalink is proxied, too.
Start, e.g., here:
https://www.lib.umich.edu/database/link/10165


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by jonearley** [comment]
Oh you're right.

https://mgetit.lib.umich.edu/resolve?rfr_id=info%3Asid%2Fwww.isinet.com%3AWoK%3AWOS&rft.atitle=Almost+structure-preserving+analysis+for+weakly+linear+damping+nonlinear+Schrodinger+equation+with+periodic+perturbation&rft.au=Yin%2C+Tingting&rft.aufirst=Weipeng&rft.aulast=Hu&rft.date=2017&rft.eissn=1878-7274&rft.epage=312&rft.genre=article&rft.issn=1007-5704&rft.jtitle=COMMUNICATIONS+IN+NONLINEAR+SCIENCE+AND+NUMERICAL+SIMULATION&rft.pages=298-312&rft.spage=298&rft.stitle=COMMUN+NONLINEAR+SCI&rft.volume=42&rft_id=info%3Adoi%2F10.1016%2Fj.cnsns.2016.05.024&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&url_ver=Z39.88-2004

https://mgetit-lib-umich-edu.proxy.lib.umich.edu/resolve?rfr_id=info%3Asid%2Fwww.isinet.com%3AWoK%3AWOS&rft.atitle=Almost+structure-preserving+analysis+for+weakly+linear+damping+nonlinear+Schrodinger+equation+with+periodic+perturbation&rft.au=Yin%2C+Tingting&rft.aufirst=Weipeng&rft.aulast=Hu&rft.date=2017&rft.eissn=1878-7274&rft.epage=312&rft.genre=article&rft.issn=1007-5704&rft.jtitle=COMMUNICATIONS+IN+NONLINEAR+SCIENCE+AND+NUMERICAL+SIMULATION&rft.pages=298-312&rft.spage=298&rft.stitle=COMMUN+NONLINEAR+SCI&rft.volume=42&rft_id=info%3Adoi%2F10.1016%2Fj.cnsns.2016.05.024&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&url_ver=Z39.88-2004

These have different permalinks so it must not be cached like I thought.

**Comment by bertrama** [comment]
I'm pretty sure that the things you're seeing is the proxy server rewriting urls.  I'll just take it out of the proxy server, and close this.

**Comment by varnum** [comment]
Yup, that seems to have done the trick. Thanks!
