### ISSUE TITLE
Some document titles are displaying as URL encoded

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#53]
See, e.g., MGet It links from here
http://web.a.ebscohost.com.proxy.lib.umich.edu/ehost/resultsadvanced?sid=db2e1868-cb0e-4dc2-af90-360d417ffb28%40sessionmgr4006&vid=2&hid=4207&bquery=random&bdata=JmRiPXBzeWgmdHlwZT0xJnNpdGU9ZWhvc3QtbGl2ZSZzY29wZT1zaXRl

Title are URL encoded when they are displayed in the interface

**Comment by jonearley** [comment]
At the template level I trust the text to be ready for display. I think this might be related to the double encoding issue (see below for examples). Umlaut might decode once and then that is now leaving us with single encoded titles being displayed as text. That's my theory. @bertrama will likely know more.

These results seem to be double encoded:
http://web.a.ebscohost.com.proxy.lib.umich.edu/ehost/results?sid=c7c72f80-d526-4018-bf47-bd16338068cf%40sessionmgr4007&vid=0&hid=4214&bquery=random&bdata=JmRiPXBzeWgmdHlwZT0xJnNpdGU9ZWhvc3QtbGl2ZSZzY29wZT1zaXRl

**Comment by varnum** [comment]
Resolved through fixing a problem on the load balancers.
