### ISSUE TITLE
Report a Problem Link Omits Referring URL

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#58]
The "DocumentID" field in the referring URL to the Report a Problem link seems to be empty from MGet It; it contains the document ID from ArticlesPlus. 

It should contain the permalink for the MGet It page.

**Comment by jonearley** [comment]
https://github.com/mlibrary/mgetit/blob/master/app/views/resolve/_found_a_problem.erb#L4

I think this is something @bertrama needs to update in Umlaut. The interface just links to the URL made available to it.

**Comment by varnum** [comment]
Thanks @bertrama for fixing this.
