### ISSUE TITLE
Disambiguation pages with only one link

### ISSUE THREAD

**Issue by bertrama** [mlibrary/mgetit#66]
[Example 1](https://mgetit.lib.umich.edu/resolve?ctx_enc=info%3Aofi%2Fenc%3AUTF-8&ctx_ver=Z39.88-2004&final_url=&id=FETCH-LOGICAL-a2011-8ff02855d075cffa7a04d5586ff898f4cdef37632eb841767dcb335279ee707c3&link_model=OpenURL&page=-1&position=-1&profile=&query=ID%3AFETCH-LOGICAL-a2011-8ff02855d075cffa7a04d5586ff898f4cdef37632eb841767dcb335279ee707c3&raw_url=ctx_ver%3DZ39.88-2004%26ctx_enc%3Dinfo%253Aofi%252Fenc%253AUTF-8%26rfr_id%3Dinfo%253Asid%252Fsummon.serialssolutions.com%26rft_val_fmt%3Dinfo%253Aofi%252Ffmt%253Akev%253Amtx%253Ajournal%26rft.genre%3Darticle%26rft.atitle%3DICESat%2Bover%2BArctic%2Bsea%2Bice%253A%2BInterpretation%2Bof%2Baltimetric%2Band%2Breflectivity%2Bprofiles%26rft.jtitle%3DJournal%2Bof%2BGeophysical%2BResearch%26rft.au%3DKwok%252C%2BR%26rft.au%3DCunningham%252C%2BG.%2BF%26rft.au%3DZwally%252C%2BH.%2BJ%26rft.au%3DYi%252C%2BD%26rft.date%3D2006%26rft.issn%3D0148-0227%26rft.eissn%3D2156-2202%26rft.volume%3D111%26rft.issue%3DC6%26rft_id%3Dinfo%3Adoi%2F10.1029%252F2005JC003175%26rft.externalDBID%3Dn%252Fa%26rft.externalDocID%3D10_1029_2005JC003175&refined_url=ctx_ver%3DZ39.88-2004%26ctx_enc%3Dinfo%253Aofi%252Fenc%253AUTF-8%26rfr_id%3Dinfo%253Asid%252Fsummon.serialssolutions.com%26rft_val_fmt%3Dinfo%253Aofi%252Ffmt%253Akev%253Amtx%253Ajournal%26rft.genre%3Darticle%26rft.atitle%3DICESat%2Bover%2BArctic%2Bsea%2Bice%253A%2BInterpretation%2Bof%2Baltimetric%2Band%2Breflectivity%2Bprofiles%26rft.jtitle%3DJournal%2Bof%2BGeophysical%2BResearch%26rft.au%3DKwok%252C%2BR%26rft.au%3DCunningham%252C%2BG.%2BF%26rft.au%3DZwally%252C%2BH.%2BJ%26rft.au%3DYi%252C%2BD%26rft.date%3D2006%26rft.issn%3D0148-0227%26rft.eissn%3D2156-2202%26rft.volume%3D111%26rft.issue%3DC6%26rft_id%3Dinfo%3Adoi%2F10.1029%252F2005JC003175%26rft.externalDBID%3Dn%252Fa%26rft.externalDocID%3D10_1029_2005JC003175&rfr_id=info%3Asid%2Fsummon.serialssolutions.com&rft.atitle=ICESat+over+Arctic+sea+ice%3A+Interpretation+of+altimetric+and+reflectivity+profiles&rft.au=Yi%2C+D&rft.date=2006&rft.eissn=2156-2202&rft.externalDBID=n%2Fa&rft.externalDocID=10_1029_2005JC003175&rft.genre=article&rft.issn=0148-0227&rft.issue=C6&rft.jtitle=Journal+of+Geophysical+Research&rft.volume=111&rft_id=info%3Adoi%2F10.1029%2F2005JC003175&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&summon_id=FETCH-LOGICAL-a2011-8ff02855d075cffa7a04d5586ff898f4cdef37632eb841767dcb335279ee707c3&type=fulltext)

**Comment by varnum** [comment]
That makes disambiguation easy. :)

Can/should we redirect de-duped disambiguation pages where there's only one resulting link to a page that looks like the normal one?

**Comment by bertrama** [comment]
Redirecting isn't necessary.  Also, this one's fixed now.
