### ISSUE TITLE
ILLiad not getting page numbers from Umlaut

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#67]
Merrie in Document Delivery about problems they've seen from Umlaut. First, a bug: Umlaut is very frequently not passing page numbers through to ILLiad, even when they appear in the MGet It screen. She's going to send me a half-dozen examples with time stamps so we can investigate.

**Comment by varnum** [comment]
From Merrie Fuller -- I've asked her for time stamps to make identifying the request a bit easier, maybe.

Transaction Number (TN): 2612333
Source: Journal of the American Pharmacists Association
Volume: 46
Number: 2
Date: 2006
Pages: 
Art. Title: Pharmacist involvement with immunizations: a decade of professional advancement.
Art. Author: Hogue, Michael D

Transaction Number (TN): 2612334
Source: Journal of the American Pharmaceutical Association (1996)
Volume: NS37
Number: 6
Date: 1997
Pages: 
Art. Title: A practical guide to establishing vaccine administration services in community pharmacies.
Art. Author: Gardner, J S

Transaction Number (TN): 2612398
Source: American journal of kidney diseases
Volume: 27
Number: 1
Date: 1996
Pages: 
Art. Title: Analgesics and the kidney: summary and recommendations to the Scientific Advisory Board of the National Kidney Foundation from an Ad Hoc Committee of the National Kidney Foundation.
Art. Author: Henrich, W L

Transaction Number (TN): 2612399
Source: American journal of kidney diseases
Volume: 28
Number: 1 suppl 1
Date: 1996
Pages: 
Art. Title: Combination analgesic involvement in the pathogenesis of analgesic nephropathy: the European perspective.
Art. Author: Elseviers, M M

**Comment by bertrama** [comment]
Updated with links.

Additional to ensuring that page numbers come through, ensure pubmed id's do too.

**Comment by bertrama** [comment]
Fixed.
