### ISSUE TITLE
Remove "do we own it or not" screen from document delivery workflow

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#68]
Document Delivery wants to kill the "do we own it" interstitial page and have all document delivery requests from Umlaut go directly to the ILL (not 7FAST) form. PARC agreed. We can do this at any point. ILLiad handles authentication and provides messages for people ineligible for the service....

**Comment by varnum** [comment]
@heidisb You'll want to know about this!

**Comment by heidisb** [comment]
Sweeeeeet. Thanks for letting me know.

**Comment by bertrama** [comment]
Done.

**Comment by varnum** [comment]
What a pleasure to get rid of an annoying screens. Thank you!
