### ISSUE TITLE
Notes field

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#70]
Had a question/concern from Kathleen Folger about the absence of the Notes field in MGet It screens, in the relatively rare instances they exist. There are only a couple dozen journals that have notes, but when they exist, they're pretty important to the user. I can't find in our notes -- did we decide to exclude the notes field intentionally, or was it so rare we simply forgot about it as the design got honed? For example, this page -- https://mgetit.lib.umich.edu/go/339944 -- should have a note like that displayed in this screen shot Kathleen provided.

![notes field from 360 link](https://cloud.githubusercontent.com/assets/17750831/21266375/efa9e5ca-c373-11e6-8207-349922cf3db0.png)

**Comment by varnum** [comment]
Kathleen shared the list of ISSNs that have notes:
https://docs.google.com/spreadsheets/d/1hvXdwtUsdDsD0dfhBdiYO6klh6wxzJUEvAgPb7oXcE0/edit#gid=0

**Comment by jonearley** [comment]
@bertrama Do you know if notes are (or could be) available to the UI?

**Comment by jonearley** [comment]
Checked with @bnhowell to see if we considered notes previously. His response: "If these unusual notes give important access related info about a holding we should absolutely include them."

**Comment by bertrama** [comment]
It should be there in `bundle.service_data[:notes]`.

**Comment by jonearley** [comment]
@bertrama when I look into `bundle.service_data` for `notes` in [this example ](https://mgetit.lib.umich.edu/resolve?rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rft.genre=Article&sid=info%3Asid%3Alib.umich.edu&rft.issn=0001-4273) I don't see them. Perhaps I'm doing something wrong?

**Comment by bertrama** [comment]
I was wrong, it's `bundle.service_data[:structured_notes]`.  But most responses don't have any notes to show.  Including the example you're looking at.  [We have notes for Factiva for sure, though](https://bertrama.www.lib.umich.edu/testapp/mgetit/resolve?ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2Fsummon.serialssolutions.com&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rft.genre=article&rft.atitle=Cigarette+blamed+for+home+fire&rft.jtitle=The+Spectator+%28Hamilton%2C+Ontario%29&rft.date=2016-06-20&rft.pub=Torstar+Syndication+Services%2C+a+division+of+Toronto+Star+Newspapers+Ltd&rft.issn=1189-9417&rft.spage=A5&rft.externalDBID=3GN&rft.externalDocID=455778529),  there's a link in this one under the "Show more"  link.

**Comment by varnum** [comment]
Thanks for releasing this -- OK to close the ticket? @jonearley
