### ISSUE TITLE
Escaped apostrophe in MGet It article title

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#79]
On the MGet It link from here:
http://proxy.lib.umich.edu/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=lii&AN=124791831&site=ehost-live&scope=site

The resulting Umlaut page has a backslash before the apostrophe in the title:
https://mgetit.lib.umich.edu/go/1442107

![screen shot 2017-08-28 at 1 25 31 pm](https://user-images.githubusercontent.com/17750831/29785109-6958a6c4-8bf4-11e7-82b8-6b5e9a2ab1ed.png)

**Comment by bertrama** [comment]
[Working as intended](http://dl2af5jf3e.search.serialssolutions.com/openurlxml?umlaut.referent_id=1441841&url_ver=Z39.88-2004&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&ctx_ver=Z39.88-2004&ctx_tim=2017-08-28T16%3A45%3A45-04%3A00&ctx_id=&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rft.atitle=Exploring+discovery%3A+The+front+door+to+your+library%5C%27s+licensed+and+digitized+content.&rft.au=Svaluto%2C+Claudio&rft.aulast=Svaluto%2C+Claudio&rft.date=20170401&rft.genre=article&rft.issn=09557490&rft.issue=1&rft.jtitle=Alexandria+%28Aldershot%29&rft.pages=56-59&rft.spage=56&rft.title=Alexandria&rft.volume=27&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rfr_id=info%3Asid%2FEBSCO%3ALibrary+Literature+%26+Information+Science+Index++%28H.W.+Wilson%29%3A124791831&version=1.0).
