### ISSUE TITLE
Survey for betas

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#8]
We need to design a survey to include in the beta of the new link resolver. Perhaps Heidi & Ben could help me with this?

It could go in a box on the right side, above or below the existing two?

**Comment by jonearley** [comment]
I can add a link to the survey in an appropriate location when ready.

**Comment by varnum** [comment]
Let's put in the placeholder text now, so we can add the link to the survey later. First box in the right column?

**Comment by jonearley** [comment]
Sure thing, I think a "site message" banner on the top fits for this well. Keeps temporary content out of the interface.

Refresh earleyj to take a look.

**Comment by varnum** [comment]
Lovely.


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by heidisb** [comment]
Happy to create it, but will need guidance from those of you on the team about what you want to evaluate/know. LMK how you want to proceed.

**Comment by varnum** [comment]
I think Ben said he'd take the lead, but I'd appreciate as many eyeballs as
possible on the questions before we launch it (especially since I may not
be able to get to it quickly).


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by heidisb** [comment]
Got it. We're chatting about it now and I'll help him as needed.

**Comment by varnum** [comment]
Survey's in place.
