### ISSUE TITLE
Promote secondary delivery options when 360 Link returns nothing

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#9]
When 360 Link does not return any links, copy the "not available online" links into the main body, with text along the lines of 

"Sorry, we aren't able to provide online access to this item. Please try the following options to get the item you are looking for."

Followed by the "Search the library catalog" and "Request document delivery (fees apply for undergraduates)" links.

This would appear in place of "Links not available" on, for example, this [resolver page](https://earleyj.www.lib.umich.edu/testapp/mgetit/resolve?ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2Fsummon.serialssolutions.com&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rft.genre=article&rft.atitle=Review+of+Cloud+Services+Discovery&rft.jtitle=Advances+in+Information+Sciences+and+Service+Sciences&rft.au=Nabeeh%2C+Nada+A&rft.au=El-Ghareeb%2C+Haitham+A&rft.au=Riad%2C+A+M&rft.date=2015-04-01&rft.issn=1976-3700&rft.eissn=2233-9345&rft.volume=7&rft.issue=2&rft.spage=28&rft.epage=28&rft.link_model=DirectLink&rft.summon_id=FETCH-LOGICAL-p578-f58de330d3e6875e2de588e7c60d274378b214e91d3106205fe13325254fbee32&rft.bookmark=ePnHCXMwPZ3bCsIwDIaLeOEE36GIt4Ue1sOup-ID7H6sTQqCOGHz_U2d8wVylbTf_yche3YYymz2c_7ucMGGVfQDGdGY2m5Lh9c7Smopd_9lxmJnKVux4-KG8zHz9jG-ga_Vws_3KZWBRsKm7nrp2pv4HQoQL0o4kW0AJF0OBh3hN2pAGwL65CSQ6DI-RK1qbBQQyzgtbUZSZtqSNsoRsVweOS1h19e4H2IxGtI89coFQgaCFK8_C-48Eg&rft.link=http%3A%2F%2Fumich.summon.serialssolutions.com%2F2.0.0%2Flink%2F0%2FeLvHCXMwrV1La8JAEB4sXgqlD9rSlxCk18Ukm81uQC2ihlJ6q3fZ7ONU1KIi_Q_90Z2JiRU8lELPYQ7Znf3m-2ZnZwAePQY91LKamSxBgeJpGqCNBKqUVOmkME54eo08eo0HuXjJ-bgB9czWantrVCyh2s4NZck7aI3BG-mCfFp8MJobRfer9RANXQ1XsD08-6k8giYGxoyK_OTbcOdhknJnewFQJpnaIxwR8h0lyl6OEcZpPH1heADSJZDmZ7De9SukepOysVOdHzxs6fhvP3YOpxVVDQZb37qAhptdwtf2MiGY-2D4Pl_boIuQNAsMkfBeu_JDRm99qTb0kyEhRrewbIMid9nu19DU7ZBZ_4_Wo_pDZX4Fk3w8GT6zaqIDWyAyMC-UdZyHlrsUdZKLrRNKOWnS0KI65lIVcZS4LLJIOtM4FN6hhI4FilhfOMfjazjRVPg_W5UPBO0NBMqEXCNHyQqq1bNGp7ywKPIio72zibyFVr3oU11Q-sisltOfJb_75fs9HCNHEttinQdoekQF14Jmudfft93g1A).

**Comment by jonearley** [comment]
I added this in and shortened the copy a little.

![screenshot-earleyj www lib umich edu 2016-08-10 14-14-51](https://cloud.githubusercontent.com/assets/1678665/17565287/d89f45a6-5f04-11e6-829e-0492af2bffdf.png)

**Comment by jonearley** [comment]
I'm going to close this issue now since secondary options are presented when online access is not available.
